# ==========================================
# 1. 基础硬件与功能配置
# ==========================================
# 开启编码器（旋钮）支持
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 开启系统电量汇报（允许电脑/手机查看键盘剩余电量）
CONFIG_ZMK_BATTERY_REPORTING=y


# ==========================================
# 2. ZMK Studio 可视化改键配置
# ==========================================
# 开启 ZMK Studio 核心支持
CONFIG_ZMK_STUDIO=y

# 强制解除 Studio 的连线锁定限制（允许通过蓝牙/有线无缝连接改键）
CONFIG_ZMK_STUDIO_LOCKING=n


# ==========================================
# 3. 蓝牙与无线连接优化
# ==========================================
# 强化蓝牙广播与连接稳定性（解决系统缓存导致的搜不到问题）
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# 自定义蓝牙广播名称
# 在双引号 "" 内填写名字（建议使用英文字母与数字，不超过15个字符）
# 示例：CONFIG_ZMK_KEYBOARD_NAME="Mpad21"
CONFIG_ZMK_KEYBOARD_NAME="MPad-21"


# ==========================================
# 开启系统级鼠标权限
CONFIG_ZMK_MOUSE=y
